Проверка классов 1
Vyacheslav-TKI/Text pull request #3
Opened 2024-04-01 18:20 UTC by Vyacheslav-TKI

Сделал:
Реализации: Color, Font, Point
Хедеры Color, Font, Point, Text

2024-04-02 12:57 UTC, MarinaPaley requested changes
Из-за кодировки

2024-04-02 12:57 UTC, MarinaPaley commented on Solver/Color.cpp
> +			throw std::logic_error("�������� ����� ������ ���� ����������������!");
Файл должен быть сохранен в кодировке `UTF-8`

2024-04-02 12:57 UTC, MarinaPaley commented on Solver/Color.h
> +	* @brief ����� ����
кодировка

2024-04-02 12:57 UTC, MarinaPaley commented on Solver/Font.cpp
> +	Font::Font(std::string name, const Color& color1, int size)
можно не называть `color1`, а называть `color`

2024-04-02 12:57 UTC, MarinaPaley commented on Solver/Font.h
> +		* @brief �������� ������
кодировка

2024-04-02 12:57 UTC, MarinaPaley commented on Solver/Point.h
> +	* @brief ����� �����.
кодировка

2024-04-02 12:57 UTC, MarinaPaley commented on Solver/Text.h
> +		* @brief ��������������� �����
кодировка

2024-04-02 12:57 UTC, MarinaPaley commented on Solver/Text.h
> +		Text(std::string data, const Font& font1);
`Text(std::string data, const Font& font);

2024-05-18 22:17 UTC, Vyacheslav-TKI commented
сделал без тестов и как поменять кодировку в VS?

2024-05-21 11:16 UTC, MarinaPaley requested changes
1. https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170
2. Все файлы открыт в `Notepad++` и переконвертировать в `UTF-8 BOM`

2024-05-21 11:16 UTC, MarinaPaley commented on Solution/main.cpp
> +			std::cerr << "��������� ��������� � �������: " << e.what() << std::endl;
Файл должен быть сохранен в кодировке `UTF-8`

2024-05-21 17:01 UTC, MarinaPaley approved these changes
Дополняйте тесты. тесты нужна все функции, на разные исходы, на операторы.

2024-05-23 17:45 UTC, merged